name: my_contact
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.0.17
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  google_fonts: ^6.2.1
  http: ^1.1.0
  hydrated_bloc: ^10.0.0
  image_picker: ^1.0.2
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.2.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/paperplane.png
